#!/usr/bin/env node
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
function parseArgs(argv) { const args = { raw: '', state: '', crawlReport: '', markAnalyzed: false }; for (let i = 0; i < argv.length; i++) { const cur = argv[i]; if (cur === '--raw') args.raw = argv[++i]; else if (cur === '--state') args.state = argv[++i]; else if (cur === '--crawl-report') args.crawlReport = argv[++i]; else if (cur === '--mark-analyzed') args.markAnalyzed = true; } if (!args.raw || !args.state) throw new Error('Usage: node analysis_gate.mjs --raw <raw.md> --state <state.json> [--crawl-report <report.json>] [--mark-analyzed]'); return args; }
function sha(text) { return crypto.createHash('sha256').update(text).digest('hex'); }
async function readJson(file) { try { return JSON.parse(await readFile(file, 'utf8')); } catch { return null; } }
async function main() { const args = parseArgs(process.argv.slice(2)); const state = await readJson(args.state); const crawlReport = args.crawlReport ? await readJson(args.crawlReport) : null; if (!crawlReport) throw new Error('--crawl-report is required for thread-first pipeline mode'); const reportHash = sha(JSON.stringify({ created_at: crawlReport.created_at, target_tab: crawlReport.target_tab, new_threads: crawlReport.new_threads, updated_threads: crawlReport.updated_threads, captured_threads: crawlReport.captured_threads })); const alreadyAnalyzed = state?.last_analyzed_hash === reportHash; const newThreads = Number(crawlReport.new_threads || 0); const updatedThreads = Number(crawlReport.updated_threads || 0); const report = { raw: args.raw, state: args.state, crawl_report: args.crawlReport, latest_increment_hash: reportHash, visible_threads: Number(crawlReport.captured_threads || 0), new_threads: newThreads, updated_threads: updatedThreads, should_analyze: !alreadyAnalyzed && newThreads > 0, reason: alreadyAnalyzed ? 'no-new-unanalysed-increment' : newThreads > 0 ? 'new-unanalysed-thread-increment' : updatedThreads > 0 ? 'updates-only-no-new-thread' : 'empty-thread-crawl' }; if (args.markAnalyzed) { await mkdir(path.dirname(args.state), { recursive: true }); await writeFile(args.state, `${JSON.stringify({ last_analyzed_hash: report.latest_increment_hash, updated_at: new Date().toISOString() }, null, 2)}
`, 'utf8'); report.marked_analyzed = true; } console.log(JSON.stringify(report, null, 2)); }
main().catch(err => { console.error(err.stack || String(err)); process.exit(1); });
